### ISSUE TITLE
Achilles Incompatibility Chat Spam Disable Request

### ISSUE THREAD

**Issue by WhiteMistral** [oOKexOo/AresModAchillesExpansion#99] opened 2017-06-26 22:33 UTC
Hello,

Super sorry to put this! First and foremost, this is an amazing mod and has led to incredible mission development and refinery. If there was a way to donate, I'd love to. If there IS, please do tell!

I would, however, like to request a small adjustment, perhaps for a personal copy that is used just between a couple of friends of mine. It's not big; I just request that the Achilles incompatibility messages not be spammed in Hint and SystemChat. I'm fully aware it's incompatible and I don't normally think of using it, but we're using ArmSTALKER and we can't get the Ares mod out of THEIR set, plus theirs is so much less functional.

If it's okay, and I'll even donate specifically for this, could you please just remove the message spam?

**Comment by CreepPork** [comment] 2017-06-28 12:58
@WhiteMistral Possibly, you could find where the issue is arising and remove the messages. Then build it, sign it with your own key and then distribute it with your friends. I believe the license allows this (sharealike).

**Comment by WhiteMistral** [comment] 2017-06-28 18:45
@CreepPork I know where the issue arises, but is there not an error that might happen if a PBO is packed with different signatures? I could just use a PBO tool, open it up, remove the line of code, then put it back in, but .. I'm afraid that might cause issues.

**Comment by CreepPork** [comment] 2017-06-28 19:26
@WhiteMistral If you tell me where is the area and I can re-pack it for you. Only issue is it if you are running a server for friends-only you'll have to place the key in the keys folder in the server.

**Comment by WhiteMistral** [comment] 2017-06-28 19:45
@CreepPork It is located in the ui_f.pbo

It is onDisplayCuratorLoad, both in displayCurator and eventHandler. It has a couple lines where it states that it will spam systemChat and Hint with incompatibility messages if it is incompatible.

And forgive me, I'm not sure how I'll place the keys in the correct fashion!

**Comment by WhiteMistral** [comment] 2017-06-28 19:48
@CreepPork For note I usually host Listen servers. I just edited the PBO file myself and it seems to work despite having the same bisign key. I'm testing to make sure my friends can join.

I may have just fixed this issue and wasted peoples' time. IF that's true, I'm very sorry. I've never edited PBOs before.

**Comment by WhiteMistral** [comment] 2017-06-28 19:53
@CreepPork Yeah. It's fixed.

I wasted everybody's time.

**Comment by CreepPork** [comment] 2017-06-28 19:53
@WhiteMistral It's there for a reason, after I found out why its there. It can definitely cause issues if you have both of them loaded. You should first consider if you can remove Ares. As you stated, that it's not possible, you should let the developers of ArmaSTALKER.

**Comment by CreepPork** [comment] 2017-06-28 19:54
@WhiteMistral No worries!

**Comment by CreepPork** [comment] 2017-06-28 20:03
@oOKexOo I believe you can close this issue, as its very user specific and shouldn't be something the main stream users should worry about.

**Comment by WhiteMistral** [comment] 2017-06-28 20:09
@oOKexOo Yes, this can be closed.

For those worrying about the compatibility fix, simply open the PBO, go to the ui_f.pbo inside, and edit both functions/displayCurator/fn_onDisplayCuratorLoad.sqf   and functions/eventHandler/fn_onDisplayCuratorLoad.sqf

Edit the part midway down the list where it says that if they detect an incompatibility, send the systemChat and Hint with sleep 1. Remove those lines altogether.

Sorry for this problem. Achilles isn't broken at all, and if anything, the tool is really smart to notify you, but I have SPECIAL NEEDS.

**Comment by oOKexOo** [comment] 2017-06-30 22:33
Well, after releasing Achilles I was annoyed by all the issue reports I got from ppl that loaded both add-ons simultaneously, so I introduced this blocker. I changed my mind by now. I don't think such a radical blocker is really required. A simple warning window that can be closed will do the job as well and is probably a much cleaner solution.

**Comment by WhiteMistral** [comment] 2017-06-30 22:35
Thanks Kex! I hope it's not being a pain, and I know it was for good reasons. I just was already aware of the fact it was incompatible so to lose access to chat etc made it all silly.

The mod is fantastic though. I can't ever see myself not using it. Thank you for everything. If I could donate to support you cause, please let me know!

**Comment by oOKexOo** [comment] 2017-07-02 21:16
1) It was an easy thing to change.
2) Thx for the offer, but this project does not accept donations.

**Comment by oOKexOo** [comment] 2017-07-06 22:51
Resolved in 0.0.8c

**Closed by oOKexOo** 2017-07-06 22:51 UTC
Labels: change, resolved
