### ISSUE TITLE
Multiple features broken APEX

### ISSUE THREAD

**Issue by BillyNovel** [oOKexOo/AresModAchillesExpansion#11] opened 2016-07-18 00:26 UTC
Hi everyone, 

Since the release of APEX, we've encountered multiple bugs on some features:
- Change player's side isn't working anymore
- Drop smokes works only sometimes
- Damage, Ammo, Behaviours aren't working on vehicules.

I'll put some error screens tomorow.

**Comment by oOKexOo** [comment] 2016-07-18 17:22
1) Yeah this was also reported in the forum. I have to check this feature.
2) Keep in mind that you cannot drop smoke while the vehicle is reloading it (some vehicles take quite a while).
3) Those features are not implemented yet. The error message probably says something similar.
Those functionalities will be integrated in future.

Actually, only 1) is a bug and got assigned.

**Comment by oOKexOo** [comment] 2016-08-27 16:33
Change player side should now work properly in Alpha 0.0.3.

**Comment by oOKexOo** [comment] 2016-09-02 12:13
The problem is fixed by now. In any other case, please create a new issue report.

**Closed by oOKexOo** 2016-09-02 12:13 UTC
Labels: resolved (await confirmation)
