### ISSUE TITLE
Trouble after 1.76 Update - 12 September 2017

### ISSUE THREAD

**Issue by tiapfy** [oOKexOo/AresModAchillesExpansion#113] opened 2017-09-12 15:01 UTC
Since the 1.76 Update, while using Zeus with Achilles mod enabled, the user may experience poor performance and frequent crashes. As we could see, this problem does happen while doing normal game master activities, without using certain modules or doing something in particular.
We experienced this issue in a multiplayer dedicated server, in an empty scenario.

Mods used:
- CBA_A3
- task_force_radio
- ace
- Ares Mod - Achilles Expansion

**Comment by RaiderSpectre** [comment] 2017-09-12 15:15
same issues here: after the last update it crashes constantly after 30-60 minutes.

**Comment by Snak3Doc** [comment] 2017-09-12 16:14
I Don't think its Achilles if you jump on the arma 3 discord troubleshooting channel you will see heaps of people talking about it there's a couple of feeback trackers open already, Deadman (tfr guy) told me to post in this one, include the RPT+mdmp+bidmp

**Comment by CreepPork** [comment] 2017-09-12 20:05
I have experienced zero issues after the new update. CBA is running fine and so is Achilles.

I imagine it's a fault with ACE as, it may be incompatible with the new version or TFAR.

**Comment by CreepPork** [comment] 2017-09-15 09:26
However, after doing some more testing, it looks like it's BI's fault.
I can reproduce a game crash when deleting objects on the map (tested it only with units alive and dead).

**Comment by Snak3Doc** [comment] 2017-09-16 04:21
fyi using the performance build .exe does fix the opening map/deleting units from map crash's, but I think it also introduces a client crash when using achiles add objects to Zeus module (still testing), might need to be aware of that when it is pushed to the main brain @oOKexOo

**Comment by CreepPork** [comment] 2017-09-16 08:18
@Snak3Doc Can you test it more and provide the .rpt, steps to reproduce because I have no issue on my end. 

Also, a good option would be to only load CBA and Achilles, to eliminate any cross-mod issues. So we don't go looking for a different mod issue.

**Comment by oOKexOo** [comment] 2017-09-16 23:48
@tiapfy and @RaiderSpectre
As @CreepPork and @Snak3Doc have stated, it is not Achilles related.
I therefore close this issue for now.

@Snak3Do
There is also little I can do about the issue with the "add objects to Zeus module", since it's likely that the issue is directly related to the corresponding script command.

**Closed by oOKexOo** 2017-09-16 23:48 UTC
Labels: BIS fault, bug
